// This file is auto-generated by scripts/generate-icons-manifest.js
// Do not edit manually

export const lucideIconNames: string[] = [
  "navigation",
  "Calendar",
  "Mail",
  "Play",
  "Wrench",
  "Rocket",
  "Palette",
  "FileText",
  "MessageSquare",
  "Code2",
  "HelpCircle",
  "BookOpen",
  "Package",
  "Container",
  "Users",
  "AtSign",
  "MessageCircle",
  "Headphones",
  "Cloud",
  "CloudLightning",
  "Shield",
  "Globe",
  "Sun",
  "Moon",
  "Grid",
  "List",
  "Pause",
  "Search",
  "X",
  "Settings",
  "Check",
  "ChevronDown",
  "ChevronUp",
  "ChevronLeft",
  "ChevronRight",
  "Menu",
  "Home",
  "User",
  "LogOut",
  "LogIn",
  "UserPlus",
  "UserMinus",
  "UserCheck",
  "UserX",
  "UserCircle",
  "UserCog",
  "UserSearch",
  "UserEdit"
];

export const brandIconNames: string[] = [
  "map",
  "github"
];

export const allIconNames: string[] = [...lucideIconNames, ...brandIconNames];
