// This file is auto-generated by scripts/generate-icons-manifest.js.
// Do not edit manually

import { AtSign, BookOpen, Calendar, Cloud, CloudLightning, Code2, Container, FileText, Globe, Headphones, HelpCircle, Mail, MessageCircle, MessageSquare, Navigation, Package, Palette, Shield, Users, Wrench } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { siGithub, siVercel, siYoutube } from 'simple-icons';
export interface BrandIconData {
  path: string;
  hex: string;
}

export const lucideIcons: Record<string, LucideIcon> = {
  AtSign,
  BookOpen,
  Calendar,
  Cloud,
  CloudLightning,
  Code2,
  Container,
  FileText,
  Globe,
  Headphones,
  HelpCircle,
  Mail,
  MessageCircle,
  MessageSquare,
  Navigation,
  Package,
  Palette,
  Shield,
  Users,
  Wrench,
};

export const brandIconsMap: Record<string, BrandIconData> = {
  "github": { path: siGithub.path, hex: siGithub.hex },
  "vercel": { path: siVercel.path, hex: siVercel.hex },
  "youtube": { path: siYoutube.path, hex: siYoutube.hex },
};

export const lucideIconNames: string[] = [
  "at-sign",
  "book-open",
  "calendar",
  "cloud",
  "cloud-lightning",
  "code2",
  "container",
  "file-text",
  "globe",
  "headphones",
  "help-circle",
  "mail",
  "message-circle",
  "message-square",
  "navigation",
  "package",
  "palette",
  "shield",
  "users",
  "wrench"
];

export const brandIconNames: string[] = [
  "github",
  "vercel",
  "youtube"
];

export const allIconNames: string[] = [...lucideIconNames, ...brandIconNames];
